version: '3.1'
services:

  postgres:
    image: postgres:13.3
    container_name: postgres_fs
    hostname: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    networks:
      - postgres_adminer
    volumes:
      - postgres:/data

  adminer:
    container_name: adminer_watcher
    hostname: adminer
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - postgres_adminer

volumes:
  postgres:
  redis:


networks:
  postgres_adminer:
    driver: bridge
